In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model  import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import graphviz 
import os
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import datasets
from sklearn.decomposition import PCA

from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC

from __future__ import print_function
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_selection import VarianceThreshold  # 方差過濾
from sklearn.metrics import recall_score

import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [2]:
df= pd.read_csv("./only_Corr_features.csv")
df

Eye_R_B_W  Eye_L_B_W  Eye_R_H6_W  Eye_L_H1_W  Eye_L_H5_W  Eye_dis_B_W  \
0      -0.371029  -0.448980   -0.866893   -0.918080    0.098274    -0.715561   
1       1.396644  -1.499499    1.332962   -0.016496    0.676106     0.214980   
2      -1.439104   0.484230    0.009343   -1.378348    0.494758    -1.548462   
3      -1.653748  -0.504374    2.759587   -1.825463    2.538630    -1.897134   
4       0.243426  -1.035791   -1.486453   -1.021156   -0.969298    -1.789011   
...          ...        ...         ...         ...         ...          ...   
67303  -0.247230   0.845882   -0.901832    0.457907   -0.499155    -0.375864   
67304   0.336898  -1.065937   -1.351670   -0.312087   -0.566462    -1.045694   
67305  -0.126210   0.098713   -1.277926    0.031775    0.029519    -0.054400   
67306   1.178550  -0.798004   -0.790639    0.514963   -1.033477     0.695431   
67307  -0.049421  -0.752788   -1.284975   -0.425240   -0.613935    -0.998181   

       Eyebrow_dis_W   N_LET_W  Eyebrow_R_H4_W  Eyebrow_L_H2_W  ...  Lip_h1_L  \
0           0.074501 -1.025311       -0.273121        0.317896  ... -0.485461   
1          -0.494539 -0.234723        2.151637        0.741030  ... -1.364071   
2          -1.184414  1.019508       -0.621587        0.675260  ... -0.409028   
3          -2.224317  3.069776        1.711365        3.198713  ... -0.943542   
4          -0.949778 -3.136693       -1.017479       -2.836990  ...  2.218981   
...              ...       ...             ...             ...  ...       ...   
67303       2.085433 -0.001246       -0.684678       -1.111386  ... -0.232581   
67304      -0.341706 -1.171122       -1.139710       -0.729043  ...  1.031585   
67305       0.022684 -0.925395       -1.129517       -0.804039  ... -1.552749   
67306       0.999174 -1.858378       -0.301002       -1.718476  ...  0.812409   
67307      -0.031247 -1.380678       -1.534513       -1.897627  ...  0.704872   

       Lip_h5_L  Lip_dh3_L  Lip_height_L  face_up_L  face_down_L  \
0     -0.638260  -1.168916     -1.429228  -0.399381     0.064321   
1     -1.649756  -0.114365     -1.331401   2.163930    -1.252541   
2      0.665220   1.289591      0.023857   0.386898     0.157466   
3      0.597671   0.288644     -0.299054   0.070247     0.287063   
4      2.824092   1.380356      0.103716   1.242597     0.827017   
...         ...        ...           ...        ...          ...   
67303 -0.455388  -0.592585      0.458105  -3.057781     1.112890   
67304  1.013650   0.511776     -0.372693  -1.909245     0.844149   
67305 -0.481648  -1.393494     -1.711341  -0.083537     0.629206   
67306  0.204526  -0.017447      2.027846  -0.400509     1.419143   
67307  0.638523   0.902799     -0.486805  -1.215145     0.187233   

       face_L_width_L  Eye_to_eyebrow_L_L  eye_to_eyebrow_R_L  Label  
0            0.643328            1.024564            1.276503   boss  
1           -2.053611           -0.569419            0.243881   boss  
2            0.393616           -1.518321           -1.391570   boss  
3           -1.495221           -2.074765           -1.844764   boss  
4            1.088651           -0.701203            0.314433   boss  
...               ...                 ...                 ...    ...  
67303        0.991555            1.693874            2.298094  sport  
67304        0.721058           -0.262786           -0.675667  sport  
67305        1.788860           -1.349675            1.083243  sport  
67306        0.225163           -0.506823           -0.119500  sport  
67307        1.548236            1.497667            1.165196  sport  

[67308 rows x 38 columns]

In [3]:
X=df.iloc[:,:-1]
y=df["Label"]

In [4]:
y=y.to_list()
a=['boss', 'doctor', 'entertainer', 'ordinary_people', 'politician', 'sport']
for i in range(len(y)):
    if y[i] in a:
        b=y[i]
        y[i]=a.index(b)
y = pd.DataFrame(y)
y1=y.to_numpy()
y=y1.ravel()

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,stratify=y)


model = DecisionTreeClassifier(class_weight="balanced")
params = {"max_leaf_nodes" : np.arange(30,60),"min_samples_leaf" : np.arange(2,10), "max_depth" : np.arange(5,15)}

model_gs = GridSearchCV(model, params, cv=5,scoring="recall_macro")
model_gs.fit(X_train, y_train)

#save best model
model_best = model_gs.best_estimator_

#check best n_neigbors value
print(model_gs.best_params_)

{'max_depth': 9, 'max_leaf_nodes': 57, 'min_samples_leaf': 9}


In [7]:
model = DecisionTreeClassifier(max_depth=9, max_leaf_nodes=57,min_samples_leaf=9,class_weight="balanced")

In [9]:
scores = cross_val_score(model, X, y, cv=5, scoring='recall_macro')
print(scores)

print("Accuracy: {} (+/- {})".format(scores.mean(), scores.std() * 2))

[0.62351234 0.66130653 0.68686822 0.73309496 0.71660487]
Accuracy: 0.6842773830563714 (+/- 0.0782559104677255)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)
recall_w = recall_score(y_test, y_pred,average="macro")

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))
print(f"recall:{recall_w}")

number of correct sample: 12166
accuracy: 0.9037290150051999
con_matrix: [[  497    95    41    88    47    28]
 [    4   112    15     3    34    12]
 [   30   103   850     4    64    36]
 [  292   152    14 10452     8    98]
 [    0    70    13     0   131    11]
 [    4    11    11     2     6   124]]
recall:0.7240661490822909
